/**
 * v2doc 공통 타입 정의
 */

// ============================================================
// 출력 포맷 타입
// ============================================================

export type OutputFormat = 'pdf' | 'md' | 'html' | 'brief';
export type ImageQuality = 'low' | 'high';
export type PDFLayout = 'vertical' | 'horizontal' | 'minimal-neon';
export type WhisperProvider = 'openai' | 'groq' | 'local';
export type SubtitleSource = 'youtube' | 'whisper';

// ============================================================
// 영상 유형 (Video Type Classification)
// ============================================================

export type VideoType =
  | 'conference_talk' // 컨퍼런스 발표
  | 'tutorial' // 튜토리얼/강좌
  | 'interview' // 인터뷰
  | 'lecture' // 강의
  | 'demo' // 제품 데모
  | 'discussion' // 토론/패널
  | 'unknown'; // 분류 불가

// ============================================================
// 챕터 (Chapter)
// ============================================================

export interface Chapter {
  title: string;
  startTime: number; // 초
  endTime: number; // 초
}

// ============================================================
// 영상 메타데이터
// ============================================================

export interface CaptionTrack {
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
}

export interface VideoMetadata {
  id: string;
  title: string;
  description: string;
  duration: number; // 초
  thumbnail: string;
  channel: string;
  uploadDate: string;
  viewCount: number;
  availableCaptions: CaptionTrack[];
  chapters?: Chapter[]; // YouTube 챕터 (있는 경우)
  videoType?: VideoType; // 영상 유형
  videoTypeConfidence?: number; // 영상 유형 판별 신뢰도 (0-1)
}

// ============================================================
// 자막 관련
// ============================================================

export interface SubtitleSegment {
  start: number; // 시작 시간 (초)
  end: number; // 종료 시간 (초)
  text: string;
}

export interface SubtitleResult {
  source: SubtitleSource;
  language: string;
  segments: SubtitleSegment[];
}

// ============================================================
// 스크린샷 관련
// ============================================================

export interface Screenshot {
  timestamp: number; // 초
  imagePath: string;
  width: number;
  height: number;
}

export interface ScreenshotOptions {
  interval: number;
  quality: ImageQuality;
  startTime?: number;
  endTime?: number;
}

// ============================================================
// PDF 관련
// ============================================================

/**
 * 핵심 포인트
 */
export interface KeyPoint {
  text: string;
  category?: 'insight' | 'action' | 'metric' | 'definition';
}

/**
 * 주요 정보
 */
export interface MainInformation {
  paragraphs: string[];
  bullets: string[];
}

/**
 * 인용문
 */
export interface NotableQuote {
  text: string;
  speaker?: string;
}

/**
 * 향상된 섹션 콘텐츠 (AI 추출 결과)
 */
export interface EnhancedSectionContent {
  translatedText?: string;
  keyPoints: string[];
  mainInformation: MainInformation;
  notableQuotes: NotableQuote[];
  oneLiner: string;
}

export interface SectionSummary {
  summary: string;
  keyPoints: string[];
  mainInformation?: MainInformation;
  notableQuotes?: string[]; // Simplified from NotableQuote[] to string[] for PDF rendering
}

export interface PDFSection {
  timestamp: number;
  screenshot: Screenshot;
  subtitles: SubtitleSegment[];
  sectionSummary?: SectionSummary;
  chapterTitle?: string; // 챕터 제목 (챕터 기반 섹션인 경우)
}

export interface ContentSummary {
  summary: string;
  keyPoints: string[];
  language: string;
}

// ============================================================
// Cover Page Metadata (Extended Summary)
// ============================================================

export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';

export interface CoverMetadata extends ContentSummary {
  // Audience & Learning Context
  targetAudience?: string; // e.g., "개발자, 테크 리드, 아키텍트"
  difficulty?: DifficultyLevel; // beginner | intermediate | advanced
  prerequisites?: string[]; // e.g., ["기본 JavaScript 지식", "React 경험"]

  // Reading Context
  estimatedReadTime?: number; // minutes (calculated from content length)

  // Discovery & SEO
  keywords?: string[]; // e.g., ["AI", "LLM", "프롬프트 엔지니어링"]

  // Value Proposition
  recommendedFor?: string[]; // e.g., ["AI 도입을 고려하는 팀"]
  benefits?: string[]; // e.g., ["AI 활용 전략 이해", "실무 적용 방법 습득"]
}

export interface PDFContent {
  metadata: VideoMetadata;
  sections: PDFSection[];
  summary?: ContentSummary;
}

// ============================================================
// Executive Brief (한 페이지 요약)
// ============================================================

export interface ExecutiveBrief {
  title: string;
  metadata: {
    channel: string;
    duration: number;
    videoType: VideoType;
    uploadDate?: string;
    videoId: string;
  };
  summary: string; // 3-5문장 핵심 요약
  keyTakeaways: string[]; // 핵심 포인트 (3-5개)
  chapterSummaries: Array<{
    title: string;
    startTime: number;
    summary: string; // 한 줄 요약
  }>;
  actionItems?: string[]; // 실행 항목 (해당시)
}

export interface PDFOptions {
  layout: PDFLayout;
  theme: string;
  includeToc: boolean;
  timestampLinks: boolean;
  searchable: boolean;
}

// ============================================================
// 프록시 정보
// ============================================================

export interface ProxyInfo {
  configured: boolean;
  validated: boolean;
  forced: boolean;
  used: boolean;
  fallbackTriggered: boolean;
}

// ============================================================
// 파이프라인 트레이스
// ============================================================

export interface TraceStep {
  name: string;
  ms: number;
  detail?: Record<string, unknown>;
}

export interface TraceResult {
  totalMs: number;
  steps: TraceStep[];
  proxy: ProxyInfo;
}

// ============================================================
// 변환 결과
// ============================================================

export interface ConvertResult {
  success: boolean;
  outputPath: string;
  metadata: VideoMetadata;
  stats: {
    pages: number;
    fileSize: number;
    duration: number;
    screenshotCount: number;
  };
  proxy?: ProxyInfo;
  trace?: TraceResult;
}

// ============================================================
// 비용 관련
// ============================================================

export interface CostEstimate {
  whisperCost: number;
  totalCost: number;
  currency: string;
  breakdown: {
    whisper?: {
      minutes: number;
      costPerMinute: number;
    };
  };
}

// ============================================================
// 파이프라인 상태
// ============================================================

export type PipelineStatus =
  | 'idle'
  | 'fetching'
  | 'processing'
  | 'generating'
  | 'complete'
  | 'error';

export interface PipelineState {
  status: PipelineStatus;
  progress: number; // 0-100
  currentStep: string;
  error?: Error;
}

export type ProgressCallback = (state: PipelineState) => void;

// ============================================================
// 에러 코드
// ============================================================

export enum ErrorCode {
  // URL 관련 (1xx)
  INVALID_URL = 100,
  VIDEO_NOT_FOUND = 101,
  VIDEO_PRIVATE = 102,
  PLAYLIST_EMPTY = 103,

  // 자막 관련 (2xx)
  NO_CAPTIONS_AVAILABLE = 200,
  WHISPER_API_ERROR = 201,
  CAPTION_PARSE_ERROR = 202,

  // 스크린샷 관련 (3xx)
  FFMPEG_NOT_INSTALLED = 300,
  SCREENSHOT_FAILED = 301,
  VIDEO_DOWNLOAD_FAILED = 302,

  // PDF 관련 (4xx)
  PDF_GENERATION_FAILED = 400,
  TEMPLATE_NOT_FOUND = 401,

  // 설정 관련 (5xx)
  CONFIG_INVALID = 500,
  API_KEY_MISSING = 501,

  // 시스템 관련 (9xx)
  DISK_FULL = 900,
  NETWORK_ERROR = 901,
  TIMEOUT = 902,
}

export class Yt2PdfError extends Error {
  constructor(
    public code: ErrorCode,
    message: string,
    public cause?: Error
  ) {
    super(message);
    this.name = 'Yt2PdfError';
  }
}
