import { OpenAPIHono, createRoute } from '@hono/zod-openapi';
import {
  AnalyzeRequestSchema,
  AnalyzeResponse,
  AnalyzeResponseSchema,
  ErrorResponseSchema,
} from '../models/job';
import { YouTubeProvider } from '../../providers/youtube';
import { CostEstimator } from '../../core/cost-estimator';
import type { AppEnv } from '../types.js';

const analyze = new OpenAPIHono<AppEnv>();

// --- OpenAPI Route Definition ---

const analyzeRoute = createRoute({
  method: 'post',
  path: '/',
  tags: ['Analysis'],
  summary: 'Analyze video metadata',
  description:
    'Analyze a YouTube video without performing full conversion. Returns metadata, available captions, chapter information, and cost/time estimates.',
  request: {
    body: {
      required: true,
      content: {
        'application/json': {
          schema: AnalyzeRequestSchema,
        },
      },
    },
  },
  responses: {
    200: {
      description: 'Analysis successful',
      content: {
        'application/json': {
          schema: AnalyzeResponseSchema,
        },
      },
    },
    400: {
      description: 'Invalid request or video not found',
      content: {
        'application/json': {
          schema: ErrorResponseSchema,
        },
      },
    },
  },
});

// --- Route Handler ---

analyze.openapi(analyzeRoute, async (c) => {
  const { url } = c.req.valid('json');

  try {
    const youtube = new YouTubeProvider();
    const metadata = await youtube.getMetadata(url);

    // Calculate cost estimate
    const hasSubtitles = metadata.availableCaptions.some((cap) => !cap.isAutoGenerated);
    const needsWhisper = !hasSubtitles;
    const whisperCost = needsWhisper ? CostEstimator.estimate(metadata.duration).whisperCost : 0;

    // Estimate processing time (rough estimate: 10% of video duration + 30s overhead)
    const processingTime = Math.ceil(metadata.duration * 0.1 + 30);

    const response: AnalyzeResponse = {
      metadata: {
        id: metadata.id,
        title: metadata.title,
        channel: metadata.channel,
        duration: metadata.duration,
        thumbnail: metadata.thumbnail,
        chapters: metadata.chapters?.map((ch) => ({
          title: ch.title,
          startTime: ch.startTime,
          endTime: ch.endTime,
        })),
        availableCaptions: metadata.availableCaptions.map((cap) => ({
          language: cap.language,
          isAutoGenerated: cap.isAutoGenerated,
        })),
      },
      estimate: {
        processingTime,
        cost: {
          whisper: whisperCost,
          total: whisperCost,
          currency: 'USD',
        },
        needsWhisper,
      },
    };

    return c.json(response, 200);
  } catch (error: unknown) {
    // eslint-disable-next-line no-console
    console.error('Analyze error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to analyze video';
    return c.json({ error: errorMessage }, 400);
  }
});

export { analyze };
