import { z } from 'zod';

// Job Status
export type JobStatus =
  | 'created'
  | 'queued'
  | 'processing'
  | 'completed'
  | 'failed'
  | 'cancelled';

// Job Options Schema
export const JobOptionsSchema = z.object({
  format: z.enum(['pdf', 'md', 'html', 'brief']).default('pdf'),
  layout: z.enum(['vertical', 'horizontal', 'minimal-neon']).default('vertical'),
  screenshotInterval: z.number().min(30).max(600).default(60), // 챕터 없을 때만 사용
  screenshotQuality: z.enum(['low', 'medium', 'high']).default('low'), // 480p/720p/1080p
  language: z.string().optional(),
  includeTranslation: z.boolean().default(false),
  includeSummary: z.boolean().default(true),
});

export type JobOptions = z.infer<typeof JobOptionsSchema>;

// Job Progress
export interface JobProgress {
  percent: number;
  currentStep: string;
  stepsCompleted: string[];
  stepsRemaining: string[];
  eta?: number;
}

// Job Result
export interface JobResult {
  outputPath: string;
  downloadUrl?: string;
  downloadUrlExpiresAt?: Date;
  fileSize: number;
  pages: number;
  screenshotCount: number;
  processingTime: number;
}

// Job Error
export interface JobError {
  code: string;
  message: string;
  retryable: boolean;
}

// Video Metadata (subset for job)
export interface JobVideoMetadata {
  title: string;
  channel: string;
  duration: number;
  thumbnail: string;
}

// Webhook Config
export interface JobWebhook {
  url: string;
  secret: string;
}

// Main Job Interface
export interface Job {
  id: string;
  userId: string;
  status: JobStatus;

  // Input
  videoUrl: string;
  videoId: string;
  options: JobOptions;

  // Metadata (populated after analysis)
  videoMetadata?: JobVideoMetadata;

  // Progress
  progress: JobProgress;

  // Result (when completed)
  result?: JobResult;

  // Error (when failed)
  error?: JobError;

  // Retry tracking
  retryCount: number;
  maxRetries: number;

  // Webhook (optional)
  webhook?: JobWebhook;

  // Timestamps
  createdAt: Date;
  queuedAt?: Date;
  startedAt?: Date;
  completedAt?: Date;
  expiresAt: Date;
}

// Create Job Request Schema
export const CreateJobRequestSchema = z.object({
  url: z.string().url().refine(
    (url) => {
      // Validate YouTube URL
      const youtubeRegex = /^(https?:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/shorts\/)/;
      return youtubeRegex.test(url);
    },
    { message: 'Invalid YouTube URL' }
  ),
  options: JobOptionsSchema.optional(),
  webhook: z.object({
    url: z.string().url(),
    secret: z.string().min(16),
  }).optional(),
});

export type CreateJobRequest = z.infer<typeof CreateJobRequestSchema>;

// Job Response (API response format)
export interface JobResponse {
  jobId: string;
  status: JobStatus;
  progress?: JobProgress;
  result?: {
    downloadUrl: string;
    expiresAt: string;
    fileSize: number;
    pages: number;
  };
  error?: JobError;
  videoMetadata?: JobVideoMetadata;
  createdAt: string;
  startedAt?: string;
  completedAt?: string;
}

// Create Job Response
export interface CreateJobResponse {
  jobId: string;
  status: JobStatus;
  estimatedDuration?: number;
  estimatedCost?: {
    whisper: number;
    total: number;
    currency: string;
  };
  statusUrl: string;
  createdAt: string;
}

// Analyze Response
export const AnalyzeRequestSchema = z.object({
  url: z.string().url(),
});

export interface AnalyzeResponse {
  metadata: {
    id: string;
    title: string;
    channel: string;
    duration: number;
    thumbnail: string;
    chapters?: Array<{ title: string; startTime: number; endTime: number }>;
    availableCaptions: Array<{ language: string; isAutoGenerated: boolean }>;
  };
  estimate: {
    processingTime: number;
    cost: {
      whisper: number;
      total: number;
      currency: string;
    };
    needsWhisper: boolean;
  };
}
